apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: roadie-demo
  description: The place to be, for great artists
  annotations:
    github.com/project-slug: devopsparadox/roadie-demo
    backstage.io/techdocs-ref: dir:. 
spec:
  type: website
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  dependsOn:
    - resource:default/artists-db
  providesApis:
    - artist-api

