apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: roadie-demo
  description: The place to be, for great artists
  annotations:
    github.com/project-slug: devopsparadox/roadie-demo
    backstage.io/techdocs-ref: dir:. 
spec:
  type: website
  lifecycle: production
  owner: vfarcic
  system: DevOpsCatalog
  dependsOn:
    - resource:default/something-db
  providesApis:
    - something-api

